"""sync providers

Revision ID: 06bc231c95e6
Revises: 29e4b29bde08
Create Date: 2026-01-14 15:57:38.241678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bc231c95e6'
down_revision = '29e4b29bde08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sync_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('sync_config', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sync_config')
    op.drop_column('projects', 'sync_type')
    # ### end Alembic commands ###
