"""remove image URIs

Revision ID: 181a9a9eab20
Revises: d358bb73f636
Create Date: 2023-03-29 17:01:00.968870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181a9a9eab20'
down_revision = 'd358bb73f636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'image_uri')
    op.drop_column('objects', 'thumbnail_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('thumbnail_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('objects', sa.Column('image_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
