"""add object lock

Revision ID: 29e4b29bde08
Revises: 8ab01349fa0c
Create Date: 2025-02-01 19:05:30.881181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e4b29bde08'
down_revision = '8ab01349fa0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('locked_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'locked_by')
    # ### end Alembic commands ###
