"""unique object URI

Revision ID: 35fffe4e3434
Revises: f8eb9b3e629a
Create Date: 2023-03-19 06:04:51.236757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fffe4e3434'
down_revision = 'f8eb9b3e629a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'objects', ['uri'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='unique')
    # ### end Alembic commands ###
