"""add project.color_table

Revision ID: 7ad95629b413
Revises: ef8299b0c950
Create Date: 2022-12-29 12:12:50.990635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad95629b413'
down_revision = 'ef8299b0c950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('color_table', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'color_table')
    # ### end Alembic commands ###
