"""add label.starred and label.count

Revision ID: 7d0f0fcfd2bc
Revises: d99eeb392fe5
Create Date: 2022-12-30 23:19:03.532674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0f0fcfd2bc'
down_revision = 'd99eeb392fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('starred', sa.Boolean(), nullable=True))
    op.add_column('labels', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'count')
    op.drop_column('labels', 'starred')
    # ### end Alembic commands ###
