"""add_delete_cascade_project_id

Revision ID: 8ab01349fa0c
Revises: 181a9a9eab20
Create Date: 2023-04-06 16:12:15.163525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab01349fa0c'
down_revision = '181a9a9eab20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('labels_project_id_fkey', 'labels', type_='foreignkey')
    op.create_foreign_key('labels_project_id_fkey', 'labels', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('objects_project_id_fkey', 'objects', type_='foreignkey')
    op.create_foreign_key('objects_project_id_fkey', 'objects', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objects_project_id_fkey', 'objects', type_='foreignkey')
    op.create_foreign_key('objects_project_id_fkey', 'objects', 'projects', ['project_id'], ['id'])
    op.drop_constraint('labels_project_id_fkey', 'labels', type_='foreignkey')
    op.create_foreign_key('labels_project_id_fkey', 'labels', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
