"""object position field

Revision ID: 9e7453295fdd
Revises: ad37e53c9a00
Create Date: 2026-01-16 15:43:17.775319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e7453295fdd"
down_revision = "ad37e53c9a00"
branch_labels = None
depends_on = None


create_indices = """
WITH positions AS (
  SELECT
    id,
    ROW_NUMBER() OVER (PARTITION BY project_id) AS n
  FROM objects
)
UPDATE objects
SET position = (
  SELECT n 
  FROM positions 
  WHERE positions.id = objects.id
);
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("objects", sa.Column("position", sa.Integer(), nullable=True))
    op.execute(create_indices)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objects", "position")
    # ### end Alembic commands ###
