"""custom project fields

Revision ID: a310324e221a
Revises: 06bc231c95e6
Create Date: 2026-01-15 00:31:36.297587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a310324e221a'
down_revision = '06bc231c95e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('custom_fields', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'custom_fields')
    # ### end Alembic commands ###
