"""object sync field

Revision ID: ad37e53c9a00
Revises: a310324e221a
Create Date: 2026-01-15 22:47:31.300100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad37e53c9a00'
down_revision = 'a310324e221a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('synced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'synced')
    # ### end Alembic commands ###
