"""add label.reference

Revision ID: af553dbdd5fb
Revises: d282d5728f25
Create Date: 2022-12-27 15:59:55.197120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af553dbdd5fb'
down_revision = 'd282d5728f25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('reference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'labels', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_column('labels', 'reference')
    # ### end Alembic commands ###
