"""add label.flags and label.count

Revision ID: bdaa73915d0f
Revises: d99eeb392fe5
Create Date: 2022-12-30 21:39:48.571108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaa73915d0f'
down_revision = 'd99eeb392fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('flags', sa.Integer(), nullable=True))
    op.add_column('labels', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'count')
    op.drop_column('labels', 'flags')
    # ### end Alembic commands ###
