"""change default value for objects.annotation_data

Revision ID: d282d5728f25
Revises: 52f2a001a868
Create Date: 2022-12-12 21:25:58.121804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd282d5728f25'
down_revision = '52f2a001a868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
