"""fixed object uuid index

Revision ID: d358bb73f636
Revises: 35fffe4e3434
Create Date: 2023-03-20 14:55:36.532358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd358bb73f636'
down_revision = '35fffe4e3434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('object_uuid', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('image_uri', sa.String(), nullable=True))
    op.drop_constraint('objects_uri_key', 'objects', type_='unique')
    op.create_index('objects_project_id_uri', 'objects', ['project_id', 'object_uuid'], unique=False)
    op.drop_column('objects', 'uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('objects_project_id_uri', table_name='objects')
    op.create_unique_constraint('objects_uri_key', 'objects', ['uri'])
    op.drop_column('objects', 'image_uri')
    op.drop_column('objects', 'object_uuid')
    # ### end Alembic commands ###
