"""allow duplicate label.reference

Revision ID: d99eeb392fe5
Revises: 7ad95629b413
Create Date: 2022-12-29 14:18:35.765592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99eeb392fe5'
down_revision = '7ad95629b413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('labels_reference_key', 'labels', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('labels_reference_key', 'labels', ['reference'])
    # ### end Alembic commands ###
