"""add label.parent_id

Revision ID: ef8299b0c950
Revises: af553dbdd5fb
Create Date: 2022-12-29 12:12:33.710646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8299b0c950'
down_revision = 'af553dbdd5fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'labels', 'labels', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_column('labels', 'parent_id')
    # ### end Alembic commands ###
