"""add object data

Revision ID: f8eb9b3e629a
Revises: 7d0f0fcfd2bc
Create Date: 2023-03-19 05:53:30.531555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8eb9b3e629a'
down_revision = '7d0f0fcfd2bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('thumbnail_uri', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('object_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'object_data')
    op.drop_column('objects', 'thumbnail_uri')
    # ### end Alembic commands ###
